R/lmerControl.R
R/modular.R
man/lmerControl.Rd

I want to be able to turn off checking that the response is constant, previously done in mkGlmerDevfun. So I've added an option "check.response.not.const" to glmerControl to allow the user to ignore that check. 
I haven't yet added the option to lmerControl, because no checking for constant response is currently done in mkLmerDevfun, but I could change this?

add control for constant response checking

---

vignettes/Theory.Rnw

Consistently use \Lambda for the left factor of relative covariance

---

README.md

Versions can make a big difference with lme4!
Added a little badge so users can see which version is on CRAN with a glance.

Add CRAN version badge to README

---

R/modular.R

I think this might fix https://github.com/lme4/lme4/issues/319.
I'm not 100% sure what's going on with `offset`, `baseOffset`, and needing to replace one with the other after you call `devfun`. But it looks like not doing this after `optimizeGlmer` calls `check.boundary` is what's been causing the numerical errors in `glmer.nb`.
Anyway, it's passing Travis on my fork, but someone should double check to see if this fix actually makes sense.

Reset offsets after stage 2 boundary check

---

man/modular.Rd

Hi, I have made a very small change to fix what I think is a typo in the 'Modular Functions for Mixed Model Fits' documentation:
Original: 'both the fixed-effects and fixed-effects part'
Fix: 'both the fixed-effects and random-effects parts'

Fix typo in man/modular.Rd

---

R/lmer.R

In the current version `refit` fails if optimizer is one of `optimx`:
```
require(lme4)
require(optimx)
sleepstudyNA <- sleepstudy
sleepstudyNA$Reaction[1:3] <- NA
fm0b <- lmer(Reaction ~ Days + (1|Subject), sleepstudyNA, 
control =lmerControl(optimizer = "optimx",optCtrl = list(method ="nlminb")))
ss0b <- refit(fm0b, simulate(fm0b))
```
This pull request adds a small patch that, in case `optimx` is the optimizer, automatically uses the `control` settings of the existing fit object which contains the information necessary (i.e., the `method` slot).
```
fm0b <- lmer(Reaction ~ Days + (1|Subject), sleepstudyNA, 
control =lmerControl(optimizer = "optimx",optCtrl = list(method ="nlminb")))
(ss0b <- refit(fm0b, simulate(fm0b)))
```  
I also tried a solution using a more general approach (i.e., …

added provision for refit to deal with 'optimx'

---

DESCRIPTION

Hi all,
I'm applying for a new job and while updating my CV I noticed that my name doesn't come up as contributor -- would you mind adding me in the next release? 
I worked with you guys in Banff back in the days and implemented the `||`-notation, amongst other things. 
Best,
F.

Add me to list of contributors plz?

---

R/predict.R

Minor change to make predict faster and avoid out of memory errors when very large numbers of random effects are in the model.
I ran into out of memory issues dealing with random intercept model where the grouping factor had hundreds of thousands of levels.
The variance structure from ranef does not appear to be used here.

models with very large numbers of random effects can cause predict to run out of memory

---

DESCRIPTION
R/lmer.R

`condVar` quickly becomes rather huge and expensive to create for models with complicated random effects, so we should not compute it unless it's actually used. It isn't used in `coef.merMod`, so let's not compute it.
All credit due to @bauer-alex who suggested this change and who also created this example: 
``` r
library(gamm4)
set.seed(0)
N <- 2000
n_i <- 20
dat <- mgcv::gamSim(1, n=N * n_i, scale=1)
dat$z <- factor(rep(1:N, each = n_i))
random.formula <- formula("~ (0 + x0 + x1 + x2 + x3 || z)")
m <- gamm4::gamm4(y ~ s(f), random = random.formula,
data = dat)
object.size(ranef(m$mer))
object.size(ranef(m$mer, condVar = FALSE))
#194960 bytes
system.time(coef(m$mer))
system.time(coef(m$mer))
```

Don't compute random effect covariance where unused

---

R/lmer.R
R/utilities.R
inst/NEWS.Rd
src/external.cpp
tests/testthat/test-formulaEval.R
tests/testthat/test-lmer.R
tests/testthat/test-methods.R

Hello,
I'm working on a new release of magrittr with a C implementation and I found an issue in our revdepchecks that boils down to this:
```r
library(magrittr)
mtcars %>% lme4::lmer("disp ~ (1 | cyl)", data = .) %>% class()
#> [1] "lmerMod"
#> attr(,"package")
#> [1] "lme4"
fn <- function(data) {
lme4::lmer("disp ~ (1 | cyl)", data = data)
}
mtcars %>% fn()
#> Error in exists(v, envir = env, inherits = FALSE) :
#>   use of NULL environment is defunct
```
A pure base R reprex can be constructed with `do.call()` (a wrapper for the C-level `Rf_eval()` function) and an artificial environment that doesn't appear in the inspectable frames:
```r
e <- new.env()
e$. <- mtcars
class(do.call(lme4::lmer, list("disp ~ (1 | cyl)", quote(.)), envir = e))
#> [1] "lmerMod"
#> attr(,"package")
#> [1] …
```

Fix data validation in corner cases

---

R/predict.R

Possibly fixes issue in [https://github.com/lme4/lme4/issues/467](https://github.com/lme4/lme4/issues/467).

Add lines to pass-through sparse argument to get.orig.levs() when using contrasts

---

R/sparsegrid.R
src/external.cpp

This is all that's needed to render the C++ code safe for #588, and you avoid extra `combinat` dependency introduced in [this commit](https://github.com/lme4/lme4/commit/f426fa2bb3dfe0b48e7e0bbc8c4633ff795301f9)

reserve C++ vector in allPerm_int

---

R/sparsegrid.R

The current last line of [`GQdk`](https://github.com/lme4/lme4/blob/master/R/sparsegrid.R#L20-L22):
https://github.com/lme4/lme4/blob/38edc87c3aa880cc9de08cae3f0398b6e90cf030/R/sparsegrid.R#L20-L22
is more dangerous than it needs to be, because it constructs a potentially enormous matrix before finally applying `unique` to condense down to the desired result. The PR implements a safer version, by applying `unique` to every iteration so that the size of the matrix never gets too out of hand. The `reprex` below also illustrates that the PR code is more efficient for larger calculations:
``` r
library(lme4)
compare_methods <- function (d = 6L, k = 4L, n = 2) {
GQNd <- GQN[[d]]
tmat <- t(GQNd[[k]])
perms <- .Call(allPerm_int, seq_len(d) + 1L, as.integer(factorial(d))) # okay here
rperms <- …
```

rewrite last lapply for GQdk

---

vignettes/lmerperf.Rmd

Ben mentioned an overhaul to the vignette; removing this line in the meantime
https://stat.ethz.ch/pipermail/r-sig-mixed-models/2021q2/029554.html

Remove vestigial object reference

---

src/external.cpp
src/respModule.cpp

Dear Ben, dear lme4 team,
The Rcpp team is trying to move towards defining STRICT_R_HEADERS by default. Please the issue ticket at https://github.com/RcppCore/Rcpp/issues/1158 for motivation and history.
Your package uses (once each in two files) PI (instead of the standard C define M_PI) and PI goes away when we set STRICT_R_HEADERS (as a #define in a header or source file, a -DSTRICT_R_HEADERS as a compiler flag, or as a #define in the Rcpp sources as we currently do). We plan to enable STRICT_R_HEADERS by the Jan 2022 release of Rcpp, and will likely offer you a define to suppress it. So if you really do not want the change you can prevent it -- see these lines in Rcpp for details:
https://github.com/RcppCore/Rcpp/blob/e79c70e76bc2a776d2d57287f7192dbdbcb292aa/inst/include/Rcpp/r/headers …

Switch PI to M_PI to support STRICT_R_HEADERS

---

tests/testthat/test-lmer.R

We can also do the following I believe:
```
skip_if_not_installed("base", "3.6.0")
skip_if_not_installed("optimx", "2018.7.10")
```
with the caveat that the subsequent of the tests in this `test_that()` unit will also be skipped

don't test optimx package version if not installed

---

R/predict.R

Error would occur when a factor was simulated, and the simulated data only contained one of the factor levels. 
Reproducible example:
```{r}
library(lme4)
set.seed(1241)
y <- factor(c(rep(0,1000),1,rep(0,1000),1),levels = c("0","1"))
x <- rep(c("A","B"),each = 1001)
mod <- glmer(y ~ 1 + (1|x),family = binomial)
simulate(mod,newdata = data.frame(x = "A"),nsim = 10)
```
Which yields the error
```
Error in factor(1 + rbinom(ntot, size = 1, prob = ftd), labels = levels(y)) : 
invalid 'labels'; length 2 should be 1 or 1
```
Fix applied which results in the correct behaviour of a factor outputted with multiple levels but all elements equal to the same element.

Fix to bug in `binomial_simfun` for factor responses

---

man/merMod-class.Rd

Corrected a small typo in the documentation.

Correction of typo in merMod-class.Rd

---

R/predict.R
man/predict.merMod.Rd
tests/testthat/test-predict.R

This PR adds an experimental feature that computes the prediction standard error for prediction with E-BLUPs. A test and documentation is also added along with it. There are some parts that can be potentially improved for computational efficiency but this is left for (near) future work.

Adding se.fit option to predict.merMod

---

.Rbuildignore
DESCRIPTION
src/lme4CholmodDecomposition.h
src/predModule.cpp

Note that these changes are entirely conditional on RcppCore/RcppEigen#131, hence `DESCRIPTION` was modified to depend on a patched **RcppEigen** and CRAN submission must be co-ordinated with @eddelbuettel.
Edit: Now I see that **RcppEigen** has `R (>= 3.6.0)` whereas **lme4** has `R (>= 3.5.0)`.  Do we know why **RcppEigen** does not support 3.5.0?

Header clean-up to fix #745

---

src/lme4CholmodDecomposition.h

The names and implementation details of factorization classes in **Matrix** may change as we generalize notably to support complex matrices.  **lme4** should use our API as much as possible to remain forward compatible.
Note that `M_chm_factor_to_SEXP` has been API since "the beginning" (**Matrix** 0.y-z), originally as a function but lately as a macro mapping to `M_cholmod_factor_as_sexp`.  Its use here does not require a stricter version dependency.

use Matrix API for (cholmod_factor *)->SEXP coercion

---

DESCRIPTION

AFAICT this macro was added in Matrix 1.6.2:
https://github.com/lme4/lme4/blob/2d82cbee952c23e2d3f8492489da7bd5a40dfb2f/src/lme4CholmodDecomposition.h#L72
It _may_ be avoidable by just copying the macro definition:
https://github.com/cran/Matrix/blob/d91a3f2149572d5e4801cb9d4c28d55ffd3642e8/inst/include/Matrix/cholmod.h#L4166-L4168
But not sure if that's hiding some other API pieces that were added at the same time.

Add missing Matrix version dependency

---

.github/workflows/R-CMD-check.yaml
R/allFit.R
inst/NEWS.Rd
man/allFit.Rd
tests/testthat/test-allFit.R

allFit Update to Allow Initialization from Model's MLE
This pull request is related to issue https://github.com/lme4/lme4/issues/724.
In summary: added a new argument `start_from_mle` to `allFit` so the user may initialize 
the refitting process using starting values from the model’s MLE. 
Example of use:
```
gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
data = cbpp, family = binomial)
allFit(show.meth.tab=TRUE) 
gm_all1 <- allFit(gm1)
ss1 <- summary(gm_all1)
gm_all2 <- allFit(gm1, start_from_mle = TRUE)
ss2 <- summary(gm_all2)
ss1
ss2
```
Extra:
1. I made minor changes in the documentation in `allFit()` to be a bit more consistent. I.e., I noticed `logical: ...` and `(logical) ...` are used. Switched to ensure all followed the former.
2.  I checked to see if …

allFit Update to Allow Initialization from Model's MLE
